### ISSUE TITLE
Lack of instructions on how to setup page.

### ISSUE THREAD

**Issue by CalvinRodo** [cds-snc/gcds-docs#116]
Hey was just playing around with the design system for something I'm building for the Dev COP and I noticed that you don't have any instructions on how to setup a basic page. 

For instance how do I structure my page so that everything isn't just aligned right up to the end of the page.

Currently this is how my page renders. 

<img width="727" alt="image" src="https://user-images.githubusercontent.com/87738/226192484-246c2858-93c0-45f4-8edd-09d644d00b95.png">

This is the basic structure of my page 

```html
<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Hackathon Generator</title>
  <!-- Font Awesome (Icons) -->
  <script src="https://kit.fontawesome.com/892cb27850.js" crossorigin="anonymous"></script>

  <!-- GC Design System -->
  <link rel="stylesheet" href="https://unpkg.com/@cdssnc/gcds-components/dist/gcds/gcds.css">
  <script type="module" src="https://unpkg.com/@cdssnc/gcds-components/dist/gcds/gcds.esm.js"></script>
  <script nomodule src="https://unpkg.com/@cdssnc/gcds-components/dist/gcds/gcds.js"></script>
</head>
<body>
<gcds-header>
</gcds-header>
<main>
  <h1>Title of page</h1>
  </main>
  <gcds-footer></gcds-footer>
  `
  <script src="static/script.js"></script>
</container>
</body>

```

**Comment by melaniebmn** [comment]
Hi @CalvinRodo,

We added a new `gcds-container` component that allows you to put all your content into a centered container to structure your page. The container has 6 different size options that you can choose from: full | xl | lg | md | sm | xs. We also have a [utility framework](https://github.com/cds-snc/gcds-utility) that allows you to style your page but we are still working on the documentation for it. We are also working on adding a patterns section to our documentation site that will cover things like page structure and how to use our components to achieve different page structures. I'm not sure though when these patterns will be ready, hopefully, this will help you in the meantime!

Here is how you can use the `gcds-container` component in your example to structure your page:

```
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Hackathon Generator</title>
    <!-- Font Awesome (Icons) -->
    <script src="https://kit.fontawesome.com/892cb27850.js" crossorigin="anonymous"></script>

    <!-- GC Design System -->
    <link rel="stylesheet" href="https://unpkg.com/@cdssnc/gcds-components/dist/gcds/gcds.css">
    <script type="module" src="https://unpkg.com/@cdssnc/gcds-components/dist/gcds/gcds.esm.js"></script>
    <script nomodule src="https://unpkg.com/@cdssnc/gcds-components/dist/gcds/gcds.js"></script>
  </head>
  <body>
    <gcds-header></gcds-header>
    <main>
      <gcds-container container="xl" centered>  
        <h1>Title of page</h1>
      </gcds-container>
    </main>
    <gcds-footer></gcds-footer>

    <script src="static/script.js"></script>
  </body>
</html>
```
