### ISSUE TITLE
Lack of instructions on how to use a design token. 

### ISSUE THREAD

**Issue by CalvinRodo** [cds-snc/gcds-docs#117]
It's really been a while since I've done any css work that's not either using something like Tailwind or the Web Experience Toolkit, so I'm really only use to using classes to style up my html. 

Would be nice to see instructions on how to use design tokens in our projects.

**Comment by abdul-CDS** [comment]
Thanks Calvin, we are looking into this and will see what we can do in future releases to make the experience better.

**Comment by daine** [comment]
Hi @CalvinRodo! Apologize for the long wait, we've added some documentation on how to use design tokens on our [README on our tokens repository](https://github.com/cds-snc/gcds-tokens?tab=readme-ov-file#how-to-use-design-tokens). I hope this helps!

**Comment by daine** [comment]
Closing this ticket, but please open a new one if the updated docs are insuffucient
