### ISSUE TITLE
Copy functionality seems to be broken

### ISSUE THREAD

**Issue by maxneuvians** [cds-snc/gcds-docs#134]
I am unable to copy code from the sample components with the following browser error:

<img width="1070" alt="Screenshot 2023-04-04 at 9 38 49 AM" src="https://user-images.githubusercontent.com/867334/229810949-dd0b1996-8bbf-4be1-a8be-114a5a29f5bd.png">

link takes me here: https://sites.google.com/a/chromium.org/dev/Home/chromium-security/deprecating-permissions-in-cross-origin-iframes

**Comment by ethanWallace** [comment]
Thanks for pointing this out! Fixed in #135
