### ISSUE TITLE
H3 header in footer

### ISSUE THREAD

**Issue by maxneuvians** [cds-snc/gcds-docs#139]
The footer component adds a `h3` tag to the code:

<img width="491" alt="Screenshot 2023-04-11 at 4 16 14 PM" src="https://user-images.githubusercontent.com/867334/231278617-6def0848-6516-4744-bb2c-ef836a158196.png">

This is causing some a11y issues where we only have an H1 and not an H2 step down.

https://www.w3.org/TR/WCAG20-TECHS/G141.html
https://dequeuniversity.com/rules/axe/4.4/heading-order

Ideally there would be an alternative to having an H2 on the page.

**Comment by dinophile** [comment]
Already fixed in [145 in gc components](https://github.com/cds-snc/gcds-components/pull/145)
