### ISSUE TITLE
Focus on menu button causes a11y errors

### ISSUE THREAD

**Issue by maxneuvians** [cds-snc/gcds-docs#140]
At some screen sizes in which the menu button is rendered we get the following error:

'Ensures interactive controls are not nested as they are not always announced by screen readers or can cause focus problems for assistive technologies'

`[{"any":[{"id":"no-focusable-content","data":null,"relatedNodes":[{"html":"<button type=\\"button\\" class=\\"button--role-primary button--solid button--regular\\" aria-expanded=\\"false\\" aria-haspopup=\\"true\\"><slot name=\\"left\\"></slot><slot></slot><slot name=\\"right\\"></slot></button>","target":[["gcds-site-menu",".mobile-menu-trigger","button[type=\\"button\\"]"]]}],"impact":"serious","message":"Element has focusable descendants"}],"all":[],"none":[],"impact":"serious","html":"<gcds-button aria-label=\\"Utiliser la touche Entrée pour ouvrir ou fermer le menu principal.\\" class=\\"mobile-menu-trigger hydrated\\" role=\\"button\\" button-role=\\"primary\\">","target":[["gcds-site-menu",".mobile-menu-trigger"]],"failureSummary":"Fix any of the following:\\n  Element has focusable descendants"}]`

**Comment by ethanWallace** [comment]
Hey @maxneuvians, thank you for flagging this! We are hoping to do a rework of the site-menu component soon and we will make sure to solve this issue at the same time.

**Comment by maxneuvians** [comment]
Thank you @ethanWallace

**Comment by dinophile** [comment]
[Logged in the DS Zenhub board](https://app.zenhub.com/workspaces/design-system-6100624a19f4cf000e46e458/issues/gh/cds-snc/design-gc-conception/373)
