### ISSUE TITLE
Add meta tag to avoid indexing

### ISSUE THREAD

**Issue by delisma** [cds-snc/gcds-docs#45]
https://github.com/cds-snc/gcds-docs/blob/9dff0222af16ce98c26b3d4c8bd40cae1421008d/src/_includes/layouts/base.njk#L7
Can we add set a meta tag `<meta name="robots" content="noindex">` to avoid indexing by search engine?

**Comment by delisma** [comment]
So it's the `dto-archive` branch that gets published? My bad then, I just looked into the main branch as the single source of truth. I'll close the comment now.

**Comment by ethanWallace** [comment]
Yes the `dto-archive` branch publishes to design.alpha.canada.ca whenever it receives a new commit
